[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzepplin/contracts=lib/openzepplin-contracts/contracts",
    "@chainlink/contracts=lib/chainlink-brownie-contracts/contracts",
]
[fuzz]
runs = 1000
depth = 128
revert_on_fail = false
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
